### ISSUE TITLE
enum not workig 

### ISSUE THREAD

**Issue by ozt88** [trenskow/isvalid#31]
```javascript
const schema = {
  required: true,
  type: String,
  enum: ['a', 'b'],
};
const data = await isvalid('a', schema);
data.should.eql('a');
```
error message
```
Error: Validator 'enum' must be an array of strings.
 at formalizeAny (node_modules\isvalid\lib\formalize.js:222:11)
 at validateAny (node_modules\isvalid\lib\validate.js:295:34)
 at Object.exports [as default] (node_modules\isvalid\lib\validate.js:383:15)
 at Context.it.only (bin\test\unit\request\reward.test.js:10:154)
```

under typescript Version 3.8.2

**Comment by trenskow** [comment]
This is obviously a bug. I will investigate and fix. Thanks.

**Comment by trenskow** [comment]
It might be causes by the error message interpreter.

You might be able to get around it if you wrap it in an error message - this this.

````javascript
const schema = {
  required: true,
  type: String,
  enum: [['a', 'b'], 'You custom error message here'],
}
````
